([rule10] of defeasible-rule
   (rule-name rule10)
   (original-rule "rule10 ( lc:case ( lc:defendant ?Defendant ) ( lc:previously_convicted \"true\" ) ) => ( not_previously_convicted ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class not_previously_convicted)
   (negated no)
   (superior)
   (deductive-rule rule10-deductive)
   (overruled-rule rule10-overruled)
   (system no)
   (support-rule rule10-support)
   (defeasibly-rule rule10-defeasibly)
   (defeated-rule nil))

([pen11] of defeasible-rule
   (rule-name pen11)
   (original-rule "pen11 ( not_previously_convicted ( defendant ?Defendant ) ) => ( to_increase_penalty ( value true ) )")
   (condition-classes)
   (conclusion-class to_increase_penalty)
   (negated no)
   (superior)
   (deductive-rule pen11-deductive)
   (overruled-rule pen11-overruled)
   (system no)
   (support-rule pen11-support)
   (defeasibly-rule pen11-defeasibly)
   (defeated-rule nil))

