([not_previously_convicted] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:num_of_victims)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:financial_status)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label not_previously_convicted)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name not_previously_convicted)
   (rules [rule10])
   (defeasible-stratum 0))

([to_increase_penalty] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:num_of_victims)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:financial_status)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label to_increase_penalty)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name to_increase_penalty)
   (rules [pen11])
   (defeasible-stratum 0))

