([rule1] of defeasible-rule
   (rule-name rule1)
   (original-rule "rule1 ( lc:case ( lc:defendant ?Defendant ) ( lc:num_of_victims ?num_of_victims ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:psychological_abuse_involved \"true\" ) ) ( test ( < ?num_of_victims 2 ) ) => ( psychological_abuse_one_victim ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_one_victim)
   (negated no)
   (superior)
   (deductive-rule rule1-deductive)
   (overruled-rule rule1-overruled)
   (system no)
   (support-rule rule1-support)
   (defeasibly-rule rule1-defeasibly)
   (defeated-rule nil))

([rule2] of defeasible-rule
   (rule-name rule2)
   (original-rule "rule2 ( lc:case ( lc:defendant ?Defendant ) ( lc:num_of_victims ?num_of_victims ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:psychological_abuse_involved \"true\" ) ) ( test ( > ?num_of_victims 1 ) ) => ( psychological_abuse_more_victims ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_more_victims)
   (negated no)
   (superior)
   (deductive-rule rule2-deductive)
   (overruled-rule rule2-overruled)
   (system no)
   (support-rule rule2-support)
   (defeasibly-rule rule2-defeasibly)
   (defeated-rule nil))

([rule3] of defeasible-rule
   (rule-name rule3)
   (original-rule "rule3 ( lc:case ( lc:defendant ?Defendant ) ( lc:num_of_victims ?num_of_victims ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:physical_abuse_involved \"true\" ) ) ( test ( < ?num_of_victims 2 ) ) => ( physical_abuse_one_victim ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class physical_abuse_one_victim)
   (negated no)
   (superior)
   (deductive-rule rule3-deductive)
   (overruled-rule rule3-overruled)
   (system no)
   (support-rule rule3-support)
   (defeasibly-rule rule3-defeasibly)
   (defeated-rule nil))

([rule4] of defeasible-rule
   (rule-name rule4)
   (original-rule "rule4 ( lc:case ( lc:defendant ?Defendant ) ( lc:num_of_victims ?num_of_victims ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:physical_abuse_involved \"true\" ) ) ( test ( > ?num_of_victims 1 ) ) => ( physical_abuse_more_victim ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class physical_abuse_more_victim)
   (negated no)
   (superior)
   (deductive-rule rule4-deductive)
   (overruled-rule rule4-overruled)
   (system no)
   (support-rule rule4-support)
   (defeasibly-rule rule4-defeasibly)
   (defeated-rule nil))

([rule5] of defeasible-rule
   (rule-name rule5)
   (original-rule "rule5 ( lc:case ( lc:defendant ?Defendant ) ( lc:num_of_victims ?num_of_victims ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:physical_abuse_involved \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:psychological_abuse_involved \"true\" ) ) ( test ( < ?num_of_victims 2 ) ) => ( physical_psychological_abuse_one_victim ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class physical_psychological_abuse_one_victim)
   (negated no)
   (superior)
   (deductive-rule rule5-deductive)
   (overruled-rule rule5-overruled)
   (system no)
   (support-rule rule5-support)
   (defeasibly-rule rule5-defeasibly)
   (defeated-rule nil))

([rule5_1] of defeasible-rule
   (rule-name rule5_1)
   (original-rule "rule5_1 ( declare ( superior rule3 ) ) ( physical_psychological_abuse_one_victim ( defendant ?Defendant ) ) => ( not ( physical_abuse_one_victim ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class physical_abuse_one_victim)
   (negated yes)
   (superior rule3)
   (deductive-rule rule5_1-deductive)
   (overruled-rule rule5_1-overruled)
   (system no)
   (support-rule rule5_1-support)
   (defeasibly-rule rule5_1-defeasibly)
   (defeated-rule rule5_1-defeated))

([rule5_2] of defeasible-rule
   (rule-name rule5_2)
   (original-rule "rule5_2 ( declare ( superior rule1 ) ) ( physical_psychological_abuse_one_victim ( defendant ?Defendant ) ) => ( not ( psychological_abuse_one_victim ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_one_victim)
   (negated yes)
   (superior rule1)
   (deductive-rule rule5_2-deductive)
   (overruled-rule rule5_2-overruled)
   (system no)
   (support-rule rule5_2-support)
   (defeasibly-rule rule5_2-defeasibly)
   (defeated-rule rule5_2-defeated))

([rule6] of defeasible-rule
   (rule-name rule6)
   (original-rule "rule6 ( lc:case ( lc:defendant ?Defendant ) ( lc:num_of_victims ?num_of_victims ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:physical_abuse_involved \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:psychological_abuse_involved \"true\" ) ) ( test ( > ?num_of_victims 1 ) ) => ( physical_psychological_abuse_more_victim ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class physical_psychological_abuse_more_victim)
   (negated no)
   (superior)
   (deductive-rule rule6-deductive)
   (overruled-rule rule6-overruled)
   (system no)
   (support-rule rule6-support)
   (defeasibly-rule rule6-defeasibly)
   (defeated-rule nil))

([rule6_1] of defeasible-rule
   (rule-name rule6_1)
   (original-rule "rule6_1 ( declare ( superior rule4 ) ) ( physical_psychological_abuse_more_victim ( defendant ?Defendant ) ) => ( not ( physical_abuse_more_victim ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class physical_abuse_more_victim)
   (negated yes)
   (superior rule4)
   (deductive-rule rule6_1-deductive)
   (overruled-rule rule6_1-overruled)
   (system no)
   (support-rule rule6_1-support)
   (defeasibly-rule rule6_1-defeasibly)
   (defeated-rule rule6_1-defeated))

([rule6_2] of defeasible-rule
   (rule-name rule6_2)
   (original-rule "rule6_2 ( declare ( superior rule2 ) ) ( physical_psychological_abuse_more_victim ( defendant ?Defendant ) ) => ( not ( psychological_abuse_more_victims ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_more_victims)
   (negated yes)
   (superior rule2)
   (deductive-rule rule6_2-deductive)
   (overruled-rule rule6_2-overruled)
   (system no)
   (support-rule rule6_2-support)
   (defeasibly-rule rule6_2-defeasibly)
   (defeated-rule rule6_2-defeated))

([rule7] of defeasible-rule
   (rule-name rule7)
   (original-rule "rule7 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_severity \"LIFE_THREATENING\" ) ) => ( life_threatening_torture ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class life_threatening_torture)
   (negated no)
   (superior)
   (deductive-rule rule7-deductive)
   (overruled-rule rule7-overruled)
   (system no)
   (support-rule rule7-support)
   (defeasibly-rule rule7-defeasibly)
   (defeated-rule nil))

([rule7_1] of defeasible-rule
   (rule-name rule7_1)
   (original-rule "rule7_1 ( declare ( superior rule5 ) ) ( life_threatening_torture ( defendant ?Defendant ) ) => ( not ( physical_psychological_abuse_one_victim ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class physical_psychological_abuse_one_victim)
   (negated yes)
   (superior rule5)
   (deductive-rule rule7_1-deductive)
   (overruled-rule rule7_1-overruled)
   (system no)
   (support-rule rule7_1-support)
   (defeasibly-rule rule7_1-defeasibly)
   (defeated-rule rule7_1-defeated))

([rule7_2] of defeasible-rule
   (rule-name rule7_2)
   (original-rule "rule7_2 ( declare ( superior rule6 ) ) ( life_threatening_torture ( defendant ?Defendant ) ) => ( not ( physical_psychological_abuse_more_victim ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class physical_psychological_abuse_more_victim)
   (negated yes)
   (superior rule6)
   (deductive-rule rule7_2-deductive)
   (overruled-rule rule7_2-overruled)
   (system no)
   (support-rule rule7_2-support)
   (defeasibly-rule rule7_2-defeasibly)
   (defeated-rule rule7_2-defeated))

([rule7_3] of defeasible-rule
   (rule-name rule7_3)
   (original-rule "rule7_3 ( declare ( superior rule4 ) ) ( life_threatening_torture ( defendant ?Defendant ) ) => ( not ( physical_abuse_more_victim ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class physical_abuse_more_victim)
   (negated yes)
   (superior rule4)
   (deductive-rule rule7_3-deductive)
   (overruled-rule rule7_3-overruled)
   (system no)
   (support-rule rule7_3-support)
   (defeasibly-rule rule7_3-defeasibly)
   (defeated-rule rule7_3-defeated))

([rule7_4] of defeasible-rule
   (rule-name rule7_4)
   (original-rule "rule7_4 ( declare ( superior rule3 ) ) ( life_threatening_torture ( defendant ?Defendant ) ) => ( not ( physical_abuse_one_victim ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class physical_abuse_one_victim)
   (negated yes)
   (superior rule3)
   (deductive-rule rule7_4-deductive)
   (overruled-rule rule7_4-overruled)
   (system no)
   (support-rule rule7_4-support)
   (defeasibly-rule rule7_4-defeasibly)
   (defeated-rule rule7_4-defeated))

([rule7_5] of defeasible-rule
   (rule-name rule7_5)
   (original-rule "rule7_5 ( declare ( superior rule2 ) ) ( life_threatening_torture ( defendant ?Defendant ) ) => ( not ( psychological_abuse_more_victim ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_more_victim)
   (negated yes)
   (superior rule2)
   (deductive-rule rule7_5-deductive)
   (overruled-rule rule7_5-overruled)
   (system no)
   (support-rule rule7_5-support)
   (defeasibly-rule rule7_5-defeasibly)
   (defeated-rule rule7_5-defeated))

([rule7_6] of defeasible-rule
   (rule-name rule7_6)
   (original-rule "rule7_6 ( declare ( superior rule1 ) ) ( life_threatening_torture ( defendant ?Defendant ) ) => ( not ( psychological_abuse_one_victim ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_one_victim)
   (negated yes)
   (superior rule1)
   (deductive-rule rule7_6-deductive)
   (overruled-rule rule7_6-overruled)
   (system no)
   (support-rule rule7_6-support)
   (defeasibly-rule rule7_6-defeasibly)
   (defeated-rule rule7_6-defeated))

([pn_psy_one_person_min] of defeasible-rule
   (rule-name pn_psy_one_person_min)
   (original-rule "pn_psy_one_person_min ( psychological_abuse_one_victim ( defendant ?Defendant ) ) => ( min_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_psy_one_person_min-deductive)
   (overruled-rule pn_psy_one_person_min-overruled)
   (system no)
   (support-rule pn_psy_one_person_min-support)
   (defeasibly-rule pn_psy_one_person_min-defeasibly)
   (defeated-rule nil))

([pn_psy_one_person_max] of defeasible-rule
   (rule-name pn_psy_one_person_max)
   (original-rule "pn_psy_one_person_max ( psychological_abuse_one_victim ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_psy_one_person_max-deductive)
   (overruled-rule pn_psy_one_person_max-overruled)
   (system no)
   (support-rule pn_psy_one_person_max-support)
   (defeasibly-rule pn_psy_one_person_max-defeasibly)
   (defeated-rule nil))

([pn_phy_one_person_min] of defeasible-rule
   (rule-name pn_phy_one_person_min)
   (original-rule "pn_phy_one_person_min ( physical_abuse_one_victim ( defendant ?Defendant ) ) => ( min_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_phy_one_person_min-deductive)
   (overruled-rule pn_phy_one_person_min-overruled)
   (system no)
   (support-rule pn_phy_one_person_min-support)
   (defeasibly-rule pn_phy_one_person_min-defeasibly)
   (defeated-rule nil))

([pn_phy_one_person_max] of defeasible-rule
   (rule-name pn_phy_one_person_max)
   (original-rule "pn_phy_one_person_max ( physical_abuse_one_victim ( defendant ?Defendant ) ) => ( max_imprisonment ( value 6 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_phy_one_person_max-deductive)
   (overruled-rule pn_phy_one_person_max-overruled)
   (system no)
   (support-rule pn_phy_one_person_max-support)
   (defeasibly-rule pn_phy_one_person_max-defeasibly)
   (defeated-rule nil))

([pn_phy_more_person_min] of defeasible-rule
   (rule-name pn_phy_more_person_min)
   (original-rule "pn_phy_more_person_min ( physical_abuse_more_victim ( defendant ?Defendant ) ) => ( min_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_phy_more_person_min-deductive)
   (overruled-rule pn_phy_more_person_min-overruled)
   (system no)
   (support-rule pn_phy_more_person_min-support)
   (defeasibly-rule pn_phy_more_person_min-defeasibly)
   (defeated-rule nil))

([pn_phy_more_person_max] of defeasible-rule
   (rule-name pn_phy_more_person_max)
   (original-rule "pn_phy_more_person_max ( physical_abuse_more_victim ( defendant ?Defendant ) ) => ( max_imprisonment ( value 6 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_phy_more_person_max-deductive)
   (overruled-rule pn_phy_more_person_max-overruled)
   (system no)
   (support-rule pn_phy_more_person_max-support)
   (defeasibly-rule pn_phy_more_person_max-defeasibly)
   (defeated-rule nil))

([pn_psy_more_person_min] of defeasible-rule
   (rule-name pn_psy_more_person_min)
   (original-rule "pn_psy_more_person_min ( psychological_abuse_more_victims ( defendant ?Defendant ) ) => ( min_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_psy_more_person_min-deductive)
   (overruled-rule pn_psy_more_person_min-overruled)
   (system no)
   (support-rule pn_psy_more_person_min-support)
   (defeasibly-rule pn_psy_more_person_min-defeasibly)
   (defeated-rule nil))

([pn_psy_more_person_max] of defeasible-rule
   (rule-name pn_psy_more_person_max)
   (original-rule "pn_psy_more_person_max ( psychological_abuse_more_victims ( defendant ?Defendant ) ) => ( max_imprisonment ( value 10 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_psy_more_person_max-deductive)
   (overruled-rule pn_psy_more_person_max-overruled)
   (system no)
   (support-rule pn_psy_more_person_max-support)
   (defeasibly-rule pn_psy_more_person_max-defeasibly)
   (defeated-rule nil))

([pn_phy_psy_one_person_min] of defeasible-rule
   (rule-name pn_phy_psy_one_person_min)
   (original-rule "pn_phy_psy_one_person_min ( physical_psychological_abuse_one_victim ( defendant ?Defendant ) ) => ( min_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_phy_psy_one_person_min-deductive)
   (overruled-rule pn_phy_psy_one_person_min-overruled)
   (system no)
   (support-rule pn_phy_psy_one_person_min-support)
   (defeasibly-rule pn_phy_psy_one_person_min-defeasibly)
   (defeated-rule nil))

([pn_phy_psy_one_person_max] of defeasible-rule
   (rule-name pn_phy_psy_one_person_max)
   (original-rule "pn_phy_psy_one_person_max ( physical_psychological_abuse_one_victim ( defendant ?Defendant ) ) => ( max_imprisonment ( value 15 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_phy_psy_one_person_max-deductive)
   (overruled-rule pn_phy_psy_one_person_max-overruled)
   (system no)
   (support-rule pn_phy_psy_one_person_max-support)
   (defeasibly-rule pn_phy_psy_one_person_max-defeasibly)
   (defeated-rule nil))

([pn_phy_psy_more_person_min] of defeasible-rule
   (rule-name pn_phy_psy_more_person_min)
   (original-rule "pn_phy_psy_more_person_min ( physical_psychological_abuse_more_victim ( defendant ?Defendant ) ) => ( min_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_phy_psy_more_person_min-deductive)
   (overruled-rule pn_phy_psy_more_person_min-overruled)
   (system no)
   (support-rule pn_phy_psy_more_person_min-support)
   (defeasibly-rule pn_phy_psy_more_person_min-defeasibly)
   (defeated-rule nil))

([pn_phy_psy_more_person_max] of defeasible-rule
   (rule-name pn_phy_psy_more_person_max)
   (original-rule "pn_phy_psy_more_person_max ( physical_psychological_abuse_more_victim ( defendant ?Defendant ) ) => ( max_imprisonment ( value 15 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_phy_psy_more_person_max-deductive)
   (overruled-rule pn_phy_psy_more_person_max-overruled)
   (system no)
   (support-rule pn_phy_psy_more_person_max-support)
   (defeasibly-rule pn_phy_psy_more_person_max-defeasibly)
   (defeated-rule nil))

([pn_life_threatening_torture_min] of defeasible-rule
   (rule-name pn_life_threatening_torture_min)
   (original-rule "pn_life_threatening_torture_min ( life_threatening_torture ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_life_threatening_torture_min-deductive)
   (overruled-rule pn_life_threatening_torture_min-overruled)
   (system no)
   (support-rule pn_life_threatening_torture_min-support)
   (defeasibly-rule pn_life_threatening_torture_min-defeasibly)
   (defeated-rule nil))

([pn_life_threatening_torture_max] of defeasible-rule
   (rule-name pn_life_threatening_torture_max)
   (original-rule "pn_life_threatening_torture_max ( life_threatening_torture ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_life_threatening_torture_max-deductive)
   (overruled-rule pn_life_threatening_torture_max-overruled)
   (system no)
   (support-rule pn_life_threatening_torture_max-support)
   (defeasibly-rule pn_life_threatening_torture_max-defeasibly)
   (defeated-rule nil))

