([psychological_abuse_one_victim] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label psychological_abuse_one_victim)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name psychological_abuse_one_victim)
   (rules [rule5_2] [rule1])
   (defeasible-stratum -1))

([psychological_abuse_more_victims] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label psychological_abuse_more_victims)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name psychological_abuse_more_victims)
   (rules [rule6_2] [rule2])
   (defeasible-stratum -1))

([physical_abuse_one_victim] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label physical_abuse_one_victim)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name physical_abuse_one_victim)
   (rules [rule5_1] [rule3])
   (defeasible-stratum -1))

([physical_abuse_more_victim] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label physical_abuse_more_victim)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name physical_abuse_more_victim)
   (rules [rule6_1] [rule4])
   (defeasible-stratum -1))

([physical_psychological_abuse_one_victim] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label physical_psychological_abuse_one_victim)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name physical_psychological_abuse_one_victim)
   (rules [rule5])
   (defeasible-stratum 0))

([physical_psychological_abuse_more_victim] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label physical_psychological_abuse_more_victim)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name physical_psychological_abuse_more_victim)
   (rules [rule6])
   (defeasible-stratum 0))

([min_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name min_imprisonment)
   (rules [pn_phy_psy_more_person_min] [pn_phy_psy_one_person_min] [pn_psy_more_person_min] [pn_phy_more_person_min] [pn_phy_one_person_min] [pn_psy_one_person_min])
   (defeasible-stratum 0))

([max_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name max_imprisonment)
   (rules [pn_phy_psy_more_person_max] [pn_phy_psy_one_person_max] [pn_psy_more_person_max] [pn_phy_more_person_max] [pn_phy_one_person_max] [pn_psy_one_person_max])
   (defeasible-stratum 0))

