([rule1] of defeasible-rule
   (rule-name rule1)
   (original-rule "rule1 ( lc:case ( lc:defendant ?Defendant ) ( lc:psychological_abuse_involved \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:physical_abuse_involved \"false\" ) ) => ( psychological_abuse ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class psychological_abuse)
   (negated no)
   (superior)
   (deductive-rule rule1-deductive)
   (overruled-rule rule1-overruled)
   (system no)
   (support-rule rule1-support)
   (defeasibly-rule rule1-defeasibly)
   (defeated-rule nil))

([rule2] of defeasible-rule
   (rule-name rule2)
   (original-rule "rule2 ( lc:case ( lc:defendant ?Defendant ) ( lc:psychological_abuse_involved \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:physical_abuse_involved \"false\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:on_duty \"true\" ) ) => ( psychological_abuse_on_duty ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_on_duty)
   (negated no)
   (superior)
   (deductive-rule rule2-deductive)
   (overruled-rule rule2-overruled)
   (system no)
   (support-rule rule2-support)
   (defeasibly-rule rule2-defeasibly)
   (defeated-rule nil))

([rule2_1] of defeasible-rule
   (rule-name rule2_1)
   (original-rule "rule2_1 ( declare ( superior rule1 ) ) ( psychological_abuse_on_duty ( defendant ?Defendant ) ) => ( not ( psychological_abuse ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse)
   (negated yes)
   (superior rule1)
   (deductive-rule rule2_1-deductive)
   (overruled-rule rule2_1-overruled)
   (system no)
   (support-rule rule2_1-support)
   (defeasibly-rule rule2_1-defeasibly)
   (defeated-rule rule2_1-defeated))

([rule3] of defeasible-rule
   (rule-name rule3)
   (original-rule "rule3 ( lc:case ( lc:defendant ?Defendant ) ( lc:num_of_defendants ?num_of_defendants ) ) => ( movement_restrictions ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class movement_restrictions)
   (negated no)
   (superior)
   (deductive-rule rule3-deductive)
   (overruled-rule rule3-overruled)
   (system no)
   (support-rule rule3-support)
   (defeasibly-rule rule3-defeasibly)
   (defeated-rule nil))

([rule3_1] of defeasible-rule
   (rule-name rule3_1)
   (original-rule "rule3_1 ( declare ( superior rule1 ) ) ( movement_restrictions ( defendant ?Defendant ) ) => ( not ( psychological_abuse ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse)
   (negated yes)
   (superior rule1)
   (deductive-rule rule3_1-deductive)
   (overruled-rule rule3_1-overruled)
   (system no)
   (support-rule rule3_1-support)
   (defeasibly-rule rule3_1-defeasibly)
   (defeated-rule rule3_1-defeated))

([rule3_2] of defeasible-rule
   (rule-name rule3_2)
   (original-rule "rule3_2 ( declare ( superior rule2 ) ) ( movement_restrictions ( defendant ?Defendant ) ) => ( not ( psychological_abuse_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_on_duty)
   (negated yes)
   (superior rule2)
   (deductive-rule rule3_2-deductive)
   (overruled-rule rule3_2-overruled)
   (system no)
   (support-rule rule3_2-support)
   (defeasibly-rule rule3_2-defeasibly)
   (defeated-rule rule3_2-defeated))

([rule4] of defeasible-rule
   (rule-name rule4)
   (original-rule "rule4 ( lc:case ( lc:defendant ?Defendant ) ( lc:on_duty \"true\" ) ) => ( movement_restrictions_on_duty ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class movement_restrictions_on_duty)
   (negated no)
   (superior)
   (deductive-rule rule4-deductive)
   (overruled-rule rule4-overruled)
   (system no)
   (support-rule rule4-support)
   (defeasibly-rule rule4-defeasibly)
   (defeated-rule nil))

([rule4_1] of defeasible-rule
   (rule-name rule4_1)
   (original-rule "rule4_1 ( declare ( superior rule1 ) ) ( movement_restrictions_on_duty ( defendant ?Defendant ) ) => ( not ( psychological_abuse ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse)
   (negated yes)
   (superior rule1)
   (deductive-rule rule4_1-deductive)
   (overruled-rule rule4_1-overruled)
   (system no)
   (support-rule rule4_1-support)
   (defeasibly-rule rule4_1-defeasibly)
   (defeated-rule rule4_1-defeated))

([rule4_2] of defeasible-rule
   (rule-name rule4_2)
   (original-rule "rule4_2 ( declare ( superior rule2 ) ) ( movement_restrictions_on_duty ( defendant ?Defendant ) ) => ( not ( psychological_abuse_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_on_duty)
   (negated yes)
   (superior rule2)
   (deductive-rule rule4_2-deductive)
   (overruled-rule rule4_2-overruled)
   (system no)
   (support-rule rule4_2-support)
   (defeasibly-rule rule4_2-defeasibly)
   (defeated-rule rule4_2-defeated))

([rule4_3] of defeasible-rule
   (rule-name rule4_3)
   (original-rule "rule4_3 ( declare ( superior rule3 ) ) ( movement_restrictions_on_duty ( defendant ?Defendant ) ) => ( not ( movement_restrictions ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions)
   (negated yes)
   (superior rule3)
   (deductive-rule rule4_3-deductive)
   (overruled-rule rule4_3-overruled)
   (system no)
   (support-rule rule4_3-support)
   (defeasibly-rule rule4_3-defeasibly)
   (defeated-rule rule4_3-defeated))

([rule5] of defeasible-rule
   (rule-name rule5)
   (original-rule "rule5 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_severity \"LIFE_THREATENING\" ) ) => ( movement_restrictions_life_threatening ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class movement_restrictions_life_threatening)
   (negated no)
   (superior)
   (deductive-rule rule5-deductive)
   (overruled-rule rule5-overruled)
   (system no)
   (support-rule rule5-support)
   (defeasibly-rule rule5-defeasibly)
   (defeated-rule nil))

([rule5_1] of defeasible-rule
   (rule-name rule5_1)
   (original-rule "rule5_1 ( declare ( superior rule1 ) ) ( movement_restrictions_life_threatening ( defendant ?Defendant ) ) => ( not ( psychological_abuse ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse)
   (negated yes)
   (superior rule1)
   (deductive-rule rule5_1-deductive)
   (overruled-rule rule5_1-overruled)
   (system no)
   (support-rule rule5_1-support)
   (defeasibly-rule rule5_1-defeasibly)
   (defeated-rule rule5_1-defeated))

([rule5_2] of defeasible-rule
   (rule-name rule5_2)
   (original-rule "rule5_2 ( declare ( superior rule2 ) ) ( movement_restrictions_life_threatening ( defendant ?Defendant ) ) => ( not ( psychological_abuse_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_on_duty)
   (negated yes)
   (superior rule2)
   (deductive-rule rule5_2-deductive)
   (overruled-rule rule5_2-overruled)
   (system no)
   (support-rule rule5_2-support)
   (defeasibly-rule rule5_2-defeasibly)
   (defeated-rule rule5_2-defeated))

([rule5_3] of defeasible-rule
   (rule-name rule5_3)
   (original-rule "rule5_3 ( declare ( superior rule3 ) ) ( movement_restrictions_life_threatening ( defendant ?Defendant ) ) => ( not ( movement_restrictions ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions)
   (negated yes)
   (superior rule3)
   (deductive-rule rule5_3-deductive)
   (overruled-rule rule5_3-overruled)
   (system no)
   (support-rule rule5_3-support)
   (defeasibly-rule rule5_3-defeasibly)
   (defeated-rule rule5_3-defeated))

([rule5_4] of defeasible-rule
   (rule-name rule5_4)
   (original-rule "rule5_4 ( declare ( superior rule4 ) ) ( movement_restrictions_life_threatening ( defendant ?Defendant ) ) => ( not ( movement_restrictions_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions_on_duty)
   (negated yes)
   (superior rule4)
   (deductive-rule rule5_4-deductive)
   (overruled-rule rule5_4-overruled)
   (system no)
   (support-rule rule5_4-support)
   (defeasibly-rule rule5_4-defeasibly)
   (defeated-rule rule5_4-defeated))

([rule6] of defeasible-rule
   (rule-name rule6)
   (original-rule "rule6 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_severity \"FATAL\" ) ) => ( movement_restrictions_death ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class movement_restrictions_death)
   (negated no)
   (superior)
   (deductive-rule rule6-deductive)
   (overruled-rule rule6-overruled)
   (system no)
   (support-rule rule6-support)
   (defeasibly-rule rule6-defeasibly)
   (defeated-rule nil))

([rule6_1] of defeasible-rule
   (rule-name rule6_1)
   (original-rule "rule6_1 ( declare ( superior rule1 ) ) ( movement_restrictions_death ( defendant ?Defendant ) ) => ( not ( psychological_abuse ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse)
   (negated yes)
   (superior rule1)
   (deductive-rule rule6_1-deductive)
   (overruled-rule rule6_1-overruled)
   (system no)
   (support-rule rule6_1-support)
   (defeasibly-rule rule6_1-defeasibly)
   (defeated-rule rule6_1-defeated))

([rule6_2] of defeasible-rule
   (rule-name rule6_2)
   (original-rule "rule6_2 ( declare ( superior rule2 ) ) ( movement_restrictions_death ( defendant ?Defendant ) ) => ( not ( psychological_abuse_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_on_duty)
   (negated yes)
   (superior rule2)
   (deductive-rule rule6_2-deductive)
   (overruled-rule rule6_2-overruled)
   (system no)
   (support-rule rule6_2-support)
   (defeasibly-rule rule6_2-defeasibly)
   (defeated-rule rule6_2-defeated))

([rule6_3] of defeasible-rule
   (rule-name rule6_3)
   (original-rule "rule6_3 ( declare ( superior rule3 ) ) ( movement_restrictions_death ( defendant ?Defendant ) ) => ( not ( movement_restrictions ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions)
   (negated yes)
   (superior rule3)
   (deductive-rule rule6_3-deductive)
   (overruled-rule rule6_3-overruled)
   (system no)
   (support-rule rule6_3-support)
   (defeasibly-rule rule6_3-defeasibly)
   (defeated-rule rule6_3-defeated))

([rule6_4] of defeasible-rule
   (rule-name rule6_4)
   (original-rule "rule6_4 ( declare ( superior rule4 ) ) ( movement_restrictions_death ( defendant ?Defendant ) ) => ( not ( movement_restrictions_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions_on_duty)
   (negated yes)
   (superior rule4)
   (deductive-rule rule6_4-deductive)
   (overruled-rule rule6_4-overruled)
   (system no)
   (support-rule rule6_4-support)
   (defeasibly-rule rule6_4-defeasibly)
   (defeated-rule rule6_4-defeated))

([rule7] of defeasible-rule
   (rule-name rule7)
   (original-rule "rule7 ( lc:case ( lc:defendant ?Defendant ) ( lc:num_of_defendants ?num_of_defendants ) ) ( test ( <= ?num_of_defendants 1 ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_severity \"BLACKMAIL\" ) ) => ( coercion_abuse ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class coercion_abuse)
   (negated no)
   (superior)
   (deductive-rule rule7-deductive)
   (overruled-rule rule7-overruled)
   (system no)
   (support-rule rule7-support)
   (defeasibly-rule rule7-defeasibly)
   (defeated-rule nil))

([rule7_1] of defeasible-rule
   (rule-name rule7_1)
   (original-rule "rule7_1 ( declare ( superior rule1 ) ) ( coercion_abuse ( defendant ?Defendant ) ) => ( not ( psychological_abuse ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse)
   (negated yes)
   (superior rule1)
   (deductive-rule rule7_1-deductive)
   (overruled-rule rule7_1-overruled)
   (system no)
   (support-rule rule7_1-support)
   (defeasibly-rule rule7_1-defeasibly)
   (defeated-rule rule7_1-defeated))

([rule7_2] of defeasible-rule
   (rule-name rule7_2)
   (original-rule "rule7_2 ( declare ( superior rule2 ) ) ( coercion_abuse ( defendant ?Defendant ) ) => ( not ( psychological_abuse_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_on_duty)
   (negated yes)
   (superior rule2)
   (deductive-rule rule7_2-deductive)
   (overruled-rule rule7_2-overruled)
   (system no)
   (support-rule rule7_2-support)
   (defeasibly-rule rule7_2-defeasibly)
   (defeated-rule rule7_2-defeated))

([rule7_3] of defeasible-rule
   (rule-name rule7_3)
   (original-rule "rule7_3 ( declare ( superior rule3 ) ) ( coercion_abuse ( defendant ?Defendant ) ) => ( not ( movement_restrictions ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions)
   (negated yes)
   (superior rule3)
   (deductive-rule rule7_3-deductive)
   (overruled-rule rule7_3-overruled)
   (system no)
   (support-rule rule7_3-support)
   (defeasibly-rule rule7_3-defeasibly)
   (defeated-rule rule7_3-defeated))

([rule7_4] of defeasible-rule
   (rule-name rule7_4)
   (original-rule "rule7_4 ( declare ( superior rule4 ) ) ( coercion_abuse ( defendant ?Defendant ) ) => ( not ( movement_restrictions_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions_on_duty)
   (negated yes)
   (superior rule4)
   (deductive-rule rule7_4-deductive)
   (overruled-rule rule7_4-overruled)
   (system no)
   (support-rule rule7_4-support)
   (defeasibly-rule rule7_4-defeasibly)
   (defeated-rule rule7_4-defeated))

([rule8] of defeasible-rule
   (rule-name rule8)
   (original-rule "rule8 ( lc:case ( lc:defendant ?Defendant ) ( lc:num_of_defendants ?num_of_defendants ) ) ( test ( >= ?num_of_defendants 2 ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_severity \"BLACKMAIL\" ) ) => ( coercion_abuse_multiple_defendant ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class coercion_abuse_multiple_defendant)
   (negated no)
   (superior)
   (deductive-rule rule8-deductive)
   (overruled-rule rule8-overruled)
   (system no)
   (support-rule rule8-support)
   (defeasibly-rule rule8-defeasibly)
   (defeated-rule nil))

([rule8_1] of defeasible-rule
   (rule-name rule8_1)
   (original-rule "rule8_1 ( declare ( superior rule1 ) ) ( coercion_abuse_multiple_defendant ( defendant ?Defendant ) ) => ( not ( psychological_abuse ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse)
   (negated yes)
   (superior rule1)
   (deductive-rule rule8_1-deductive)
   (overruled-rule rule8_1-overruled)
   (system no)
   (support-rule rule8_1-support)
   (defeasibly-rule rule8_1-defeasibly)
   (defeated-rule rule8_1-defeated))

([rule8_2] of defeasible-rule
   (rule-name rule8_2)
   (original-rule "rule8_2 ( declare ( superior rule2 ) ) ( coercion_abuse_multiple_defendant ( defendant ?Defendant ) ) => ( not ( psychological_abuse_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_on_duty)
   (negated yes)
   (superior rule2)
   (deductive-rule rule8_2-deductive)
   (overruled-rule rule8_2-overruled)
   (system no)
   (support-rule rule8_2-support)
   (defeasibly-rule rule8_2-defeasibly)
   (defeated-rule rule8_2-defeated))

([rule8_3] of defeasible-rule
   (rule-name rule8_3)
   (original-rule "rule8_3 ( declare ( superior rule3 ) ) ( coercion_abuse_multiple_defendant ( defendant ?Defendant ) ) => ( not ( movement_restrictions ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions)
   (negated yes)
   (superior rule3)
   (deductive-rule rule8_3-deductive)
   (overruled-rule rule8_3-overruled)
   (system no)
   (support-rule rule8_3-support)
   (defeasibly-rule rule8_3-defeasibly)
   (defeated-rule rule8_3-defeated))

([rule8_4] of defeasible-rule
   (rule-name rule8_4)
   (original-rule "rule8_4 ( declare ( superior rule4 ) ) ( coercion_abuse_multiple_defendant ( defendant ?Defendant ) ) => ( not ( movement_restrictions_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions_on_duty)
   (negated yes)
   (superior rule4)
   (deductive-rule rule8_4-deductive)
   (overruled-rule rule8_4-overruled)
   (system no)
   (support-rule rule8_4-support)
   (defeasibly-rule rule8_4-defeasibly)
   (defeated-rule rule8_4-defeated))

([rule9] of defeasible-rule
   (rule-name rule9)
   (original-rule "rule9 ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_severity \"BLACKMAIL\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:on_duty \"true\" ) ) => ( coercion_abuse_on_duty ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class coercion_abuse_on_duty)
   (negated no)
   (superior)
   (deductive-rule rule9-deductive)
   (overruled-rule rule9-overruled)
   (system no)
   (support-rule rule9-support)
   (defeasibly-rule rule9-defeasibly)
   (defeated-rule nil))

([rule9_1] of defeasible-rule
   (rule-name rule9_1)
   (original-rule "rule9_1 ( declare ( superior rule1 ) ) ( coercion_abuse_on_duty ( defendant ?Defendant ) ) => ( not ( psychological_abuse ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse)
   (negated yes)
   (superior rule1)
   (deductive-rule rule9_1-deductive)
   (overruled-rule rule9_1-overruled)
   (system no)
   (support-rule rule9_1-support)
   (defeasibly-rule rule9_1-defeasibly)
   (defeated-rule rule9_1-defeated))

([rule9_2] of defeasible-rule
   (rule-name rule9_2)
   (original-rule "rule9_2 ( declare ( superior rule2 ) ) ( coercion_abuse_on_duty ( defendant ?Defendant ) ) => ( not ( psychological_abuse_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_on_duty)
   (negated yes)
   (superior rule2)
   (deductive-rule rule9_2-deductive)
   (overruled-rule rule9_2-overruled)
   (system no)
   (support-rule rule9_2-support)
   (defeasibly-rule rule9_2-defeasibly)
   (defeated-rule rule9_2-defeated))

([rule9_3] of defeasible-rule
   (rule-name rule9_3)
   (original-rule "rule9_3 ( declare ( superior rule3 ) ) ( coercion_abuse_on_duty ( defendant ?Defendant ) ) => ( not ( movement_restrictions ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions)
   (negated yes)
   (superior rule3)
   (deductive-rule rule9_3-deductive)
   (overruled-rule rule9_3-overruled)
   (system no)
   (support-rule rule9_3-support)
   (defeasibly-rule rule9_3-defeasibly)
   (defeated-rule rule9_3-defeated))

([rule9_4] of defeasible-rule
   (rule-name rule9_4)
   (original-rule "rule9_4 ( declare ( superior rule4 ) ) ( coercion_abuse_on_duty ( defendant ?Defendant ) ) => ( not ( movement_restrictions_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions_on_duty)
   (negated yes)
   (superior rule4)
   (deductive-rule rule9_4-deductive)
   (overruled-rule rule9_4-overruled)
   (system no)
   (support-rule rule9_4-support)
   (defeasibly-rule rule9_4-defeasibly)
   (defeated-rule rule9_4-defeated))

([rule9_7] of defeasible-rule
   (rule-name rule9_7)
   (original-rule "rule9_7 ( declare ( superior rule7 ) ) ( coercion_abuse_on_duty ( defendant ?Defendant ) ) => ( not ( coercion_abuse ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class coercion_abuse)
   (negated yes)
   (superior rule7)
   (deductive-rule rule9_7-deductive)
   (overruled-rule rule9_7-overruled)
   (system no)
   (support-rule rule9_7-support)
   (defeasibly-rule rule9_7-defeasibly)
   (defeated-rule rule9_7-defeated))

([rule9_8] of defeasible-rule
   (rule-name rule9_8)
   (original-rule "rule9_8 ( declare ( superior rule8 ) ) ( coercion_abuse_on_duty ( defendant ?Defendant ) ) => ( not ( coercion_abuse_multiple_defendant ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class coercion_abuse_multiple_defendant)
   (negated yes)
   (superior rule8)
   (deductive-rule rule9_8-deductive)
   (overruled-rule rule9_8-overruled)
   (system no)
   (support-rule rule9_8-support)
   (defeasibly-rule rule9_8-defeasibly)
   (defeated-rule rule9_8-defeated))

([rule10] of defeasible-rule
   (rule-name rule10)
   (original-rule "rule10 ( lc:case ( lc:defendant ?Defendant ) ( lc:num_of_victims ?num_of_victims ) ) ( test ( >= ?num_of_victims 2 ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:injury_severity \"BLACKMAIL\" ) ) => ( coercion_abuse_multiple_victims ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class coercion_abuse_multiple_victims)
   (negated no)
   (superior)
   (deductive-rule rule10-deductive)
   (overruled-rule rule10-overruled)
   (system no)
   (support-rule rule10-support)
   (defeasibly-rule rule10-defeasibly)
   (defeated-rule nil))

([rule10_1] of defeasible-rule
   (rule-name rule10_1)
   (original-rule "rule10_1 ( declare ( superior rule1 ) ) ( coercion_abuse_multiple_victims ( defendant ?Defendant ) ) => ( not ( psychological_abuse ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse)
   (negated yes)
   (superior rule1)
   (deductive-rule rule10_1-deductive)
   (overruled-rule rule10_1-overruled)
   (system no)
   (support-rule rule10_1-support)
   (defeasibly-rule rule10_1-defeasibly)
   (defeated-rule rule10_1-defeated))

([rule10_2] of defeasible-rule
   (rule-name rule10_2)
   (original-rule "rule10_2 ( declare ( superior rule2 ) ) ( coercion_abuse_multiple_victims ( defendant ?Defendant ) ) => ( not ( psychological_abuse_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class psychological_abuse_on_duty)
   (negated yes)
   (superior rule2)
   (deductive-rule rule10_2-deductive)
   (overruled-rule rule10_2-overruled)
   (system no)
   (support-rule rule10_2-support)
   (defeasibly-rule rule10_2-defeasibly)
   (defeated-rule rule10_2-defeated))

([rule10_3] of defeasible-rule
   (rule-name rule10_3)
   (original-rule "rule10_3 ( declare ( superior rule3 ) ) ( coercion_abuse_multiple_victims ( defendant ?Defendant ) ) => ( not ( movement_restrictions ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions)
   (negated yes)
   (superior rule3)
   (deductive-rule rule10_3-deductive)
   (overruled-rule rule10_3-overruled)
   (system no)
   (support-rule rule10_3-support)
   (defeasibly-rule rule10_3-defeasibly)
   (defeated-rule rule10_3-defeated))

([rule10_4] of defeasible-rule
   (rule-name rule10_4)
   (original-rule "rule10_4 ( declare ( superior rule4 ) ) ( coercion_abuse_multiple_victims ( defendant ?Defendant ) ) => ( not ( movement_restrictions_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class movement_restrictions_on_duty)
   (negated yes)
   (superior rule4)
   (deductive-rule rule10_4-deductive)
   (overruled-rule rule10_4-overruled)
   (system no)
   (support-rule rule10_4-support)
   (defeasibly-rule rule10_4-defeasibly)
   (defeated-rule rule10_4-defeated))

([rule10_7] of defeasible-rule
   (rule-name rule10_7)
   (original-rule "rule10_7 ( declare ( superior rule7 ) ) ( coercion_abuse_multiple_victims ( defendant ?Defendant ) ) => ( not ( coercion_abuse ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class coercion_abuse)
   (negated yes)
   (superior rule7)
   (deductive-rule rule10_7-deductive)
   (overruled-rule rule10_7-overruled)
   (system no)
   (support-rule rule10_7-support)
   (defeasibly-rule rule10_7-defeasibly)
   (defeated-rule rule10_7-defeated))

([rule10_8] of defeasible-rule
   (rule-name rule10_8)
   (original-rule "rule10_8 ( declare ( superior rule8 ) ) ( coercion_abuse_multiple_victims ( defendant ?Defendant ) ) => ( not ( coercion_abuse_multiple_defendant ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class coercion_abuse_multiple_defendant)
   (negated yes)
   (superior rule8)
   (deductive-rule rule10_8-deductive)
   (overruled-rule rule10_8-overruled)
   (system no)
   (support-rule rule10_8-support)
   (defeasibly-rule rule10_8-defeasibly)
   (defeated-rule rule10_8-defeated))

([rule10_9] of defeasible-rule
   (rule-name rule10_9)
   (original-rule "rule10_9 ( declare ( superior rule9 ) ) ( coercion_abuse_multiple_victims ( defendant ?Defendant ) ) => ( not ( coercion_abuse_on_duty ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class coercion_abuse_on_duty)
   (negated yes)
   (superior rule9)
   (deductive-rule rule10_9-deductive)
   (overruled-rule rule10_9-overruled)
   (system no)
   (support-rule rule10_9-support)
   (defeasibly-rule rule10_9-defeasibly)
   (defeated-rule rule10_9-defeated))

([pn_psy_abuse_min] of defeasible-rule
   (rule-name pn_psy_abuse_min)
   (original-rule "pn_psy_abuse_min ( psychological_abuse ( defendant ?Defendant ) ) => ( min_imprisonment ( value 0 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_psy_abuse_min-deductive)
   (overruled-rule pn_psy_abuse_min-overruled)
   (system no)
   (support-rule pn_psy_abuse_min-support)
   (defeasibly-rule pn_psy_abuse_min-defeasibly)
   (defeated-rule nil))

([pn_psy_abuse_max] of defeasible-rule
   (rule-name pn_psy_abuse_max)
   (original-rule "pn_psy_abuse_max ( psychological_abuse ( defendant ?Defendant ) ) => ( max_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_psy_abuse_max-deductive)
   (overruled-rule pn_psy_abuse_max-overruled)
   (system no)
   (support-rule pn_psy_abuse_max-support)
   (defeasibly-rule pn_psy_abuse_max-defeasibly)
   (defeated-rule nil))

([pn_psy_abuse_on_duty_min] of defeasible-rule
   (rule-name pn_psy_abuse_on_duty_min)
   (original-rule "pn_psy_abuse_on_duty_min ( psychological_abuse_on_duty ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_psy_abuse_on_duty_min-deductive)
   (overruled-rule pn_psy_abuse_on_duty_min-overruled)
   (system no)
   (support-rule pn_psy_abuse_on_duty_min-support)
   (defeasibly-rule pn_psy_abuse_on_duty_min-defeasibly)
   (defeated-rule nil))

([pn_psy_abuse_on_duty_max] of defeasible-rule
   (rule-name pn_psy_abuse_on_duty_max)
   (original-rule "pn_psy_abuse_on_duty_max ( psychological_abuse_on_duty ( defendant ?Defendant ) ) => ( max_imprisonment ( value 8 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_psy_abuse_on_duty_max-deductive)
   (overruled-rule pn_psy_abuse_on_duty_max-overruled)
   (system no)
   (support-rule pn_psy_abuse_on_duty_max-support)
   (defeasibly-rule pn_psy_abuse_on_duty_max-defeasibly)
   (defeated-rule nil))

([pn_movement_restrct_min] of defeasible-rule
   (rule-name pn_movement_restrct_min)
   (original-rule "pn_movement_restrct_min ( movement_restrictions ( defendant ?Defendant ) ) => ( min_imprisonment ( value 0 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_movement_restrct_min-deductive)
   (overruled-rule pn_movement_restrct_min-overruled)
   (system no)
   (support-rule pn_movement_restrct_min-support)
   (defeasibly-rule pn_movement_restrct_min-defeasibly)
   (defeated-rule nil))

([pn_movement_restrct_max] of defeasible-rule
   (rule-name pn_movement_restrct_max)
   (original-rule "pn_movement_restrct_max ( movement_restrictions ( defendant ?Defendant ) ) => ( max_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_movement_restrct_max-deductive)
   (overruled-rule pn_movement_restrct_max-overruled)
   (system no)
   (support-rule pn_movement_restrct_max-support)
   (defeasibly-rule pn_movement_restrct_max-defeasibly)
   (defeated-rule nil))

([pn_movement_restrct_on_duty_min] of defeasible-rule
   (rule-name pn_movement_restrct_on_duty_min)
   (original-rule "pn_movement_restrct_on_duty_min ( movement_restrictions_on_duty ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_movement_restrct_on_duty_min-deductive)
   (overruled-rule pn_movement_restrct_on_duty_min-overruled)
   (system no)
   (support-rule pn_movement_restrct_on_duty_min-support)
   (defeasibly-rule pn_movement_restrct_on_duty_min-defeasibly)
   (defeated-rule nil))

([pn_movement_restrct_on_duty_max] of defeasible-rule
   (rule-name pn_movement_restrct_on_duty_max)
   (original-rule "pn_movement_restrct_on_duty_max ( movement_restrictions_on_duty ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_movement_restrct_on_duty_max-deductive)
   (overruled-rule pn_movement_restrct_on_duty_max-overruled)
   (system no)
   (support-rule pn_movement_restrct_on_duty_max-support)
   (defeasibly-rule pn_movement_restrct_on_duty_max-defeasibly)
   (defeated-rule nil))

([pn_movement_restrct_life_threatening_min] of defeasible-rule
   (rule-name pn_movement_restrct_life_threatening_min)
   (original-rule "pn_movement_restrct_life_threatening_min ( movement_restrictions_life_threatening ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_movement_restrct_life_threatening_min-deductive)
   (overruled-rule pn_movement_restrct_life_threatening_min-overruled)
   (system no)
   (support-rule pn_movement_restrct_life_threatening_min-support)
   (defeasibly-rule pn_movement_restrct_life_threatening_min-defeasibly)
   (defeated-rule nil))

([pn_movement_restrct_life_threatening_max] of defeasible-rule
   (rule-name pn_movement_restrct_life_threatening_max)
   (original-rule "pn_movement_restrct_life_threatening_max ( movement_restrictions_life_threatening ( defendant ?Defendant ) ) => ( max_imprisonment ( value 8 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_movement_restrct_life_threatening_max-deductive)
   (overruled-rule pn_movement_restrct_life_threatening_max-overruled)
   (system no)
   (support-rule pn_movement_restrct_life_threatening_max-support)
   (defeasibly-rule pn_movement_restrct_life_threatening_max-defeasibly)
   (defeated-rule nil))

([pn_movement_restrct_death_min] of defeasible-rule
   (rule-name pn_movement_restrct_death_min)
   (original-rule "pn_movement_restrct_death_min ( movement_restrictions_death ( defendant ?Defendant ) ) => ( min_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_movement_restrct_death_min-deductive)
   (overruled-rule pn_movement_restrct_death_min-overruled)
   (system no)
   (support-rule pn_movement_restrct_death_min-support)
   (defeasibly-rule pn_movement_restrct_death_min-defeasibly)
   (defeated-rule nil))

([pn_movement_restrct_death_max] of defeasible-rule
   (rule-name pn_movement_restrct_death_max)
   (original-rule "pn_movement_restrct_death_max ( movement_restrictions_death ( defendant ?Defendant ) ) => ( max_imprisonment ( value 12 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_movement_restrct_death_max-deductive)
   (overruled-rule pn_movement_restrct_death_max-overruled)
   (system no)
   (support-rule pn_movement_restrct_death_max-support)
   (defeasibly-rule pn_movement_restrct_death_max-defeasibly)
   (defeated-rule nil))

([pn_coercion_abuse_min] of defeasible-rule
   (rule-name pn_coercion_abuse_min)
   (original-rule "pn_coercion_abuse_min ( coercion_abuse ( defendant ?Defendant ) ) => ( min_imprisonment ( value 0 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_coercion_abuse_min-deductive)
   (overruled-rule pn_coercion_abuse_min-overruled)
   (system no)
   (support-rule pn_coercion_abuse_min-support)
   (defeasibly-rule pn_coercion_abuse_min-defeasibly)
   (defeated-rule nil))

([pn_coercion_abuse_max] of defeasible-rule
   (rule-name pn_coercion_abuse_max)
   (original-rule "pn_coercion_abuse_max ( coercion_abuse ( defendant ?Defendant ) ) => ( max_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_coercion_abuse_max-deductive)
   (overruled-rule pn_coercion_abuse_max-overruled)
   (system no)
   (support-rule pn_coercion_abuse_max-support)
   (defeasibly-rule pn_coercion_abuse_max-defeasibly)
   (defeated-rule nil))

([pn_coercion_abuse_multiple_defendant_min] of defeasible-rule
   (rule-name pn_coercion_abuse_multiple_defendant_min)
   (original-rule "pn_coercion_abuse_multiple_defendant_min ( coercion_abuse_multiple_defendant ( defendant ?Defendant ) ) => ( min_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_coercion_abuse_multiple_defendant_min-deductive)
   (overruled-rule pn_coercion_abuse_multiple_defendant_min-overruled)
   (system no)
   (support-rule pn_coercion_abuse_multiple_defendant_min-support)
   (defeasibly-rule pn_coercion_abuse_multiple_defendant_min-defeasibly)
   (defeated-rule nil))

([pn_coercion_abuse_multiple_defendant_max] of defeasible-rule
   (rule-name pn_coercion_abuse_multiple_defendant_max)
   (original-rule "pn_coercion_abuse_multiple_defendant_max ( coercion_abuse_multiple_defendant ( defendant ?Defendant ) ) => ( max_imprisonment ( value 12 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_coercion_abuse_multiple_defendant_max-deductive)
   (overruled-rule pn_coercion_abuse_multiple_defendant_max-overruled)
   (system no)
   (support-rule pn_coercion_abuse_multiple_defendant_max-support)
   (defeasibly-rule pn_coercion_abuse_multiple_defendant_max-defeasibly)
   (defeated-rule nil))

([pn_coercion_abuse_on_duty_min] of defeasible-rule
   (rule-name pn_coercion_abuse_on_duty_min)
   (original-rule "pn_coercion_abuse_on_duty_min ( coercion_abuse_on_duty ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_coercion_abuse_on_duty_min-deductive)
   (overruled-rule pn_coercion_abuse_on_duty_min-overruled)
   (system no)
   (support-rule pn_coercion_abuse_on_duty_min-support)
   (defeasibly-rule pn_coercion_abuse_on_duty_min-defeasibly)
   (defeated-rule nil))

([pn_coercion_abuse_on_duty_max] of defeasible-rule
   (rule-name pn_coercion_abuse_on_duty_max)
   (original-rule "pn_coercion_abuse_on_duty_max ( coercion_abuse_on_duty ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_coercion_abuse_on_duty_max-deductive)
   (overruled-rule pn_coercion_abuse_on_duty_max-overruled)
   (system no)
   (support-rule pn_coercion_abuse_on_duty_max-support)
   (defeasibly-rule pn_coercion_abuse_on_duty_max-defeasibly)
   (defeated-rule nil))

([pn_coercion_abuse_multiple_victims_min] of defeasible-rule
   (rule-name pn_coercion_abuse_multiple_victims_min)
   (original-rule "pn_coercion_abuse_multiple_victims_min ( coercion_abuse_multiple_victims ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_coercion_abuse_multiple_victims_min-deductive)
   (overruled-rule pn_coercion_abuse_multiple_victims_min-overruled)
   (system no)
   (support-rule pn_coercion_abuse_multiple_victims_min-support)
   (defeasibly-rule pn_coercion_abuse_multiple_victims_min-defeasibly)
   (defeated-rule nil))

([pn_coercion_abuse_multiple_victims_max] of defeasible-rule
   (rule-name pn_coercion_abuse_multiple_victims_max)
   (original-rule "pn_coercion_abuse_multiple_victims_max ( coercion_abuse_multiple_victims ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pn_coercion_abuse_multiple_victims_max-deductive)
   (overruled-rule pn_coercion_abuse_multiple_victims_max-overruled)
   (system no)
   (support-rule pn_coercion_abuse_multiple_victims_max-support)
   (defeasibly-rule pn_coercion_abuse_multiple_victims_max-defeasibly)
   (defeated-rule nil))

