([psychological_abuse_one_victim-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label psychological_abuse_one_victim)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule7_6-deductive-gen340] [rule5_2-deductive-gen330] [rule1-deductive-gen324]))

([psychological_abuse_more_victims-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label psychological_abuse_more_victims)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule6_2-deductive-gen333] [rule2-deductive-gen325]))

([physical_abuse_one_victim-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label physical_abuse_one_victim)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule7_4-deductive-gen338] [rule5_1-deductive-gen329] [rule3-deductive-gen326]))

([physical_abuse_more_victim-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label physical_abuse_more_victim)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule7_3-deductive-gen337] [rule6_1-deductive-gen332] [rule4-deductive-gen327]))

([physical_psychological_abuse_one_victim-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label physical_psychological_abuse_one_victim)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule7_1-deductive-gen335] [rule5-deductive-gen328]))

([physical_psychological_abuse_more_victim-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label physical_psychological_abuse_more_victim)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule7_2-deductive-gen336] [rule6-deductive-gen331]))

([life_threatening_torture-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label life_threatening_torture)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule7-deductive-gen334]))

([psychological_abuse_more_victim-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label psychological_abuse_more_victim)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule7_5-deductive-gen339]))

([min_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pn_life_threatening_torture_min-deductive-gen353] [pn_phy_psy_more_person_min-deductive-gen351] [pn_phy_psy_one_person_min-deductive-gen349] [pn_psy_more_person_min-deductive-gen347] [pn_phy_more_person_min-deductive-gen345] [pn_phy_one_person_min-deductive-gen343] [pn_psy_one_person_min-deductive-gen341]))

([max_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:num_of_victims)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pn_life_threatening_torture_max-deductive-gen354] [pn_phy_psy_more_person_max-deductive-gen352] [pn_phy_psy_one_person_max-deductive-gen350] [pn_psy_more_person_max-deductive-gen348] [pn_phy_more_person_max-deductive-gen346] [pn_phy_one_person_max-deductive-gen344] [pn_psy_one_person_max-deductive-gen342]))

