([psychological_abuse-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:on_duty)
   (lc:num_of_victims)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label psychological_abuse)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule8_1-deductive-gen479] [rule7_1-deductive-gen474] [rule6_1-deductive-gen469] [rule5_1-deductive-gen464] [rule4_1-deductive-gen460] [rule3_1-deductive-gen457] [rule2_1-deductive-gen455] [rule1-deductive-gen453]))

([psychological_abuse_on_duty-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:on_duty)
   (lc:num_of_victims)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label psychological_abuse_on_duty)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule8_2-deductive-gen480] [rule7_2-deductive-gen475] [rule6_2-deductive-gen470] [rule5_2-deductive-gen465] [rule4_2-deductive-gen461] [rule3_2-deductive-gen458] [rule2-deductive-gen454]))

([movement_restrictions-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:on_duty)
   (lc:num_of_victims)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label movement_restrictions)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule8_3-deductive-gen481] [rule7_3-deductive-gen476] [rule6_3-deductive-gen471] [rule5_3-deductive-gen466] [rule4_3-deductive-gen462] [rule3-deductive-gen456]))

([movement_restrictions_on_duty-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:on_duty)
   (lc:num_of_victims)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label movement_restrictions_on_duty)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule8_4-deductive-gen482] [rule7_4-deductive-gen477] [rule6_4-deductive-gen472] [rule5_4-deductive-gen467] [rule4-deductive-gen459]))

([movement_restrictions_life_threatening-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:on_duty)
   (lc:num_of_victims)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label movement_restrictions_life_threatening)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule5-deductive-gen463]))

([movement_restrictions_death-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:on_duty)
   (lc:num_of_victims)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label movement_restrictions_death)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule6-deductive-gen468]))

([coercion_abuse-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:on_duty)
   (lc:num_of_victims)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label coercion_abuse)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule8_7-deductive-gen483] [rule7-deductive-gen473]))

([coercion_abuse_multiple_defendant-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:on_duty)
   (lc:num_of_victims)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label coercion_abuse_multiple_defendant)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule8-deductive-gen478]))

([min_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:on_duty)
   (lc:num_of_victims)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pn_coercion_abuse_multiple_defendant_min-deductive-gen498] [pn_coercion_abuse_min-deductive-gen496] [pn_movement_restrct_death_min-deductive-gen494] [pn_movement_restrct_life_threatening_min-deductive-gen492] [pn_movement_restrct_on_duty_min-deductive-gen490] [pn_movement_restrct_min-deductive-gen488] [pn_psy_abuse_on_duty_min-deductive-gen486] [pn_psy_abuse_min-deductive-gen484]))

([max_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:previously_convicted)
   (lc:psychological_abuse_involved)
   (lc:physical_abuse_involved)
   (lc:financial_status)
   (lc:injury_severity)
   (lc:on_duty)
   (lc:num_of_victims)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pn_coercion_abuse_multiple_defendant_max-deductive-gen499] [pn_coercion_abuse_max-deductive-gen497] [pn_movement_restrct_death_max-deductive-gen495] [pn_movement_restrct_life_threatening_max-deductive-gen493] [pn_movement_restrct_on_duty_max-deductive-gen491] [pn_movement_restrct_max-deductive-gen489] [pn_psy_abuse_on_duty_max-deductive-gen487] [pn_psy_abuse_max-deductive-gen485]))

