( defclass psychological_abuse_one_victim ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass psychological_abuse_more_victims ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass physical_abuse_one_victim ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass physical_abuse_more_victim ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass physical_psychological_abuse_one_victim ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass physical_psychological_abuse_more_victim ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass min_imprisonment ( is-a DERIVED-CLASS ) ( slot value ( type INTEGER ) ) )
( defclass max_imprisonment ( is-a DERIVED-CLASS ) ( slot value ( type INTEGER ) ) )
